Шемякин Никита Александрович
itmo2022-verstka/task-2 pull request #1
Opened 2022-11-02 00:20 UTC by JelluSandro

реализация основного дз + дополнительного

2023-01-02 10:09 UTC, trixartem requested changes

2023-01-02 10:09 UTC, trixartem commented on ping-tinder/src/index.css
> +header h1 {
А почему не класс?

2023-01-02 10:09 UTC, trixartem commented on ping-tinder/src/index.css
> +  color: white;
Лучше hex

2023-01-02 10:09 UTC, trixartem commented on ping-tinder/src/index.css
> +  top: 20vh;
Странные единицы, потому что позиционирование absolute, а отталкивается на 20% от высоты вьюпорта. Может % использовать?

2023-01-02 10:09 UTC, trixartem commented on ping-tinder/src/index.html
> +    <main>
На широких экранах все расползается
![image](https://user-images.githubusercontent.com/2376007/210217419-30d2c748-9eb2-474b-a4db-94ec40fbf627.png)

2023-01-02 10:10 UTC, trixartem commented on ping-tinder/src/index.css
> +  position: fixed;
Точно Fixed нужен?

2023-01-06 23:27 UTC, JelluSandro commented on ping-tinder/src/index.css
> +  position: fixed;
да там иначе хедер на топ 0 не встанет

2023-01-06 23:28 UTC, JelluSandro commented
исправил все замечания

2023-01-10 12:50 UTC, trixartem commented
✅ Принято

2023-01-10 12:50 UTC, closed without merging