Максонов Артем
itmo2022-verstka/task-2 pull request #11
Opened 2022-12-03 13:19 UTC by BloodMagicLord

2023-01-03 09:49 UTC, trixartem requested changes
Хочу отметить, что код очень аккуратный и верстка тоже, не хватает обработки случая в горизонтальном режиме. Надо исправить небольшие комментарии

2023-01-03 09:49 UTC, trixartem commented on ping-tinder/src/index.html
> +  <div class="content">
не хватает семантики

2023-01-03 09:49 UTC, trixartem commented on ping-tinder/src/index.css
> +img {
Точно для все картинок на странице нужны такие свойства?

2023-01-03 09:49 UTC, trixartem commented on ping-tinder/src/script.js
> +  let curBrightness = 0;
🔥 анимация, жаль что не на css

2023-01-07 15:17 UTC, BloodMagicLord commented
Исправил недочёты.

2023-01-10 13:05 UTC, trixartem commented
✅ Принято. В следующий раз не забывай про семантические теги.

2023-01-10 13:05 UTC, closed without merging