init
itmo2022-verstka/task-2 pull request #15
Opened 2023-01-07 01:34 UTC by SunsetMT

2023-01-17 19:20 UTC, trixartem commented
- Слишком большие отступы
- Одна иконка не показывается
![image](https://user-images.githubusercontent.com/2376007/212992671-2b6a9855-ad82-4fed-a48e-074ec40730e0.png)

2023-01-17 19:24 UTC, trixartem requested changes

2023-01-17 19:24 UTC, trixartem commented on ping-tinder/src/index.css
> +  transform:translate(-50%,-50%);
А почему не flex?

2023-01-17 19:24 UTC, trixartem commented on ping-tinder/src/index.css
> +.control-panel img {
Вместо такого каскада лучше использовать уникальный класс для картинки

2023-01-17 19:24 UTC, trixartem commented on ping-tinder/src/index.html
> +  <script src="app.js"></script>
Скрипт лучше в конец

2023-01-17 19:24 UTC, trixartem commented on ping-tinder/src/index.html
> +        <img src="img/pig7.jpg" alt="" class="pig-img">
Кажется alt не должен быть пустым - в картинке все таки есть смысл

2023-01-17 19:24 UTC, trixartem commented on ping-tinder/src/app.js
> +function nextCard() {
Если уже js, то просится сделать доп. задание

2023-01-20 11:24 UTC, SunsetMT commented on ping-tinder/src/index.css
> +  transform:translate(-50%,-50%);
Я центрировать пытался. Пофиксил работает и без этого кода

2023-01-20 11:26 UTC, SunsetMT commented on ping-tinder/src/app.js
> +function nextCard() {
Сделал

2023-01-20 11:27 UTC, SunsetMT commented
Сделал доп задание исправил ошибки

2023-01-23 08:51 UTC, trixartem commented
✅ Принято

2023-01-23 08:51 UTC, closed without merging