Купчик Антон
itmo2022-verstka/task-2 pull request #17
Opened 2023-01-09 15:44 UTC by tattosha01

PigTinder

2023-03-15 19:54 UTC, trixartem requested changes
На десктопе не влазит в экран
![image](https://user-images.githubusercontent.com/2376007/225427341-8858e045-9020-4cb2-a1ea-9b37ac8ed3f1.png)

2023-03-15 19:54 UTC, trixartem commented on ping-tinder/src/index.html
> +      <span>PigTinder</span>
Не хвататет семантики

2023-03-15 19:54 UTC, trixartem commented on ping-tinder/src/index.css
> +  margin-left: auto;
Можно одним свойством

2023-03-19 18:47 UTC, tattosha01 commented on ping-tinder/src/index.html
> +      <span>PigTinder</span>
Поправил

2023-03-19 18:48 UTC, tattosha01 commented
> На десктопе не влазит в экран ![image](https://user-images.githubusercontent.com/2376007/225427341-8858e045-9020-4cb2-a1ea-9b37ac8ed3f1.png)

Поправил. Не знаю, зачем у меня было всё такое огромное...

2023-03-19 19:00 UTC, tattosha01 commented on ping-tinder/src/index.css
> +  margin-left: auto;
Да, действительно. Исправил: объединил три в одно

2023-03-22 20:22 UTC, trixartem commented
✅ Принято

2023-03-22 20:22 UTC, closed without merging