Бессонницын Евгений
itmo2022-verstka/task-2 pull request #2
Opened 2022-11-02 12:46 UTC by Turukmokto

Свайп реализован чуть больше, чем по заданию: для двух вариантов верстки (вертикальной и горизонтальной) сделаны по 3 соответствующих расположению кнопок варианта.

2023-01-02 10:26 UTC, trixartem requested changes
Есть небольшие замечания в коде - есть лишние свойства, которые или переопределяются или не работаю.

🔥 за анимацию смены слайда

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.html
> +	<script>
script лучше в конце класть

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +.pig#pig1 {
тут и так указывается id, а он уникален - класс не нужен

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	bottom: 0%;
кажется это лишнее

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	z-index: 1;
А можно без z-index?

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	left: 0px;
Просто 0

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	position: static;
а зачем указывать static?

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	vertical-align: center;
Кажется это лишнее свойство.

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	margin-left: auto;
Может просто margin: auto?

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	box-shadow: 0 0 10px rgba(256,0,0,0.7);
rgba(255

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +.info_block li {
Лучше дать уникальные классы и указать через запятую, если есть общие свойства. Иначе приходится переопределять свойства

2023-01-02 10:26 UTC, trixartem commented on ping-tinder/src/index.css
> +	margin-top: 25%;
Лучше указывать в px, если это значение действительно адаптивно не меняется, что бывает редко

2023-01-03 19:10 UTC, Turukmokto commented
@trixartem Все замечания поправил, посмотрите, пожалуйста, как будет возможность

1 + js код вставить в конце body
2 + убрать класс, так как используется id
3 + лишний кусочек: удалил padding и z-index
4 + вопрос про необходимость z-index: согласен, он не нужен, это осталось от моей первой версии кода, потом переделал

5 + 0px -> 0
6 + вопрос про необходимость static: ой, да, это я что-то совсем невнимательный, он же по умолчанию static)
7 + убрать лишнее свойство: да, vertical align не нужен
8 + margin-left/right -> margin

9 + rgba 255: ну, тут правда глупейшая опечатка, справедливо)
10 + вместо li сделать классы: я поправил, просто конкретно в данном макете у меня эти свойства верны для всех li, поэтому изначально так сделал

11 + указать значение в пикселях: я не совсем согласен, что в данном случае проценты неуместны, потому что я хочу, чтобы на более вытянутых телефонных экранах картинка была +- ближе к центру (не задиралась вверх на странице), а менять каждый раз это свойство у info_block в различных ориентациях как-то не хотелось. Я переделал на стандартный неизменный отступ в 90px, но мне кажется, что с 25% было чуточку лучше.

Ещё убрал дебажный backgroung green в одном месте)

2023-01-06 15:53 UTC, trixartem commented
> 11 + указать значение в пикселях: я не совсем согласен, что в данном случае проценты неуместны, потому что я хочу, чтобы на более вытянутых телефонных экранах картинка была +- ближе к центру (не задиралась вверх на странице), а менять каждый раз это свойство у info_block в различных ориентациях как-то не хотелось. Я переделал на стандартный неизменный отступ в 90px, но мне кажется, что с 25% было чуточку лучше.

Я ж правильно понял, что хочется выровнять по вертикали?
Можно же использовать стандартные способы, что бы выровнять по вертикали, например flex и тогда пропорциональные отступы будут не нужны.

2023-01-06 15:54 UTC, trixartem commented
✅ В остальном все ок

2023-01-06 15:54 UTC, closed without merging