Потехин Денис
itmo2022-verstka/task-2 pull request #3
Opened 2022-11-02 18:01 UTC by DenisPotekhin2002

Дз 2

2023-01-02 10:33 UTC, trixartem requested changes

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.html
> +    <div class="picture">
Не хватает семантики

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.html
> +          <div class="description">Лара, 1 год</div>
тут тоже не хватает семантики

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.css
> +  background-color: lightgray;
лучше указывать в HEX

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.css
> +  max-width: 100%;
Это точно на все картинки должно распространяться? опасно так делать - если на странице появятся еще картинки, то правило будет применяться

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.css
> +  z-index: 2;
z-index точно нужен?

2023-01-02 10:33 UTC, trixartem commented on ping-tinder/src/index.html
> +    PigTinder
тянет на h1

2023-01-02 10:47 UTC, DenisPotekhin2002 commented on ping-tinder/src/index.html
> +    <div class="picture">
Вы имеете в виду, использовать не div, а какой-то более осмысленный элемент? Я думал, но не придумал, что. Это же не article и не section. Могу сделать figure, наверное, - он, как я понимаю, используется как обертка над картинками. Ок будет?

2023-01-02 10:54 UTC, DenisPotekhin2002 commented on ping-tinder/src/index.css
> +  z-index: 2;
изначально это было для того, чтобы заголовок всегда был сверху при масштабировании. Но потом я сделал, чтобы картинка на него и так никогда не налезала, так что да, и правда, уже не нужен

2023-01-02 11:09 UTC, DenisPotekhin2002 commented on ping-tinder/src/index.html
> +    <div class="picture">
Сделал section. И вообще убрал div-ы везде, кроме лайка-суперлайка-дизлайка, там решил оставить

2023-01-10 13:23 UTC, DenisPotekhin2002 commented
Вроде всё исправил, кроме z-index, который оставил на всякий случай

2023-01-15 10:25 UTC, trixartem commented
✅  Принято

2023-01-15 10:25 UTC, closed without merging