Галибов Михаил
itmo2022-verstka/task-2 pull request #4
Opened 2022-11-04 12:28 UTC by Gram3r

2023-01-02 10:44 UTC, trixartem requested changes
Старайся применять знания по flex и Grid, а не только fixed, absolute

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.html
> +  <script>
script лучше в конце унести

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.html
> +  <p>PigTinder</p>
тянет на h1

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +  z-index: 10;
точно нужен z-index? и Fixed?

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +header p {
Не очень хорошо на все теги задавать стили - лучше указывать для классов

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +.main .posts .post p{
Можно просто задать уникальный класс

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +  position: fixed;
А здесь для чего fixed?

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +  position: fixed;
Можно flex/grid обойтись

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +  margin: 15% 20% 15% 20%;
В процентах получилось интересно, но не надежно. Лучше при помощи медиа выражений для разных экранов указывать разные отступы и размеры

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +.main .posts .post {
а зачем такой каскад?

2023-01-02 10:44 UTC, trixartem commented on ping-tinder/src/index.css
> +  position: absolute;
Для чего вырывать из потока. Используйте fex/grid

2023-01-05 12:07 UTC, Gram3r commented on ping-tinder/src/index.html
> +  <script>
fixed

2023-01-05 12:09 UTC, Gram3r commented on ping-tinder/src/index.html
> +  <p>PigTinder</p>
fixed

2023-01-05 12:11 UTC, Gram3r commented on ping-tinder/src/index.css
> +  z-index: 10;
fixed

2023-01-05 12:11 UTC, Gram3r commented on ping-tinder/src/index.css
> +header p {
fixed

2023-01-05 12:13 UTC, Gram3r commented on ping-tinder/src/index.css
> +.main .posts .post p{
fixed

2023-01-05 12:14 UTC, Gram3r commented on ping-tinder/src/index.css
> +.main .posts .post {
fixed

2023-01-05 12:34 UTC, Gram3r commented on ping-tinder/src/index.css
> +  position: fixed;
fixed

2023-01-05 12:49 UTC, Gram3r commented on ping-tinder/src/index.css
> +  position: absolute;
fixed

2023-01-05 13:00 UTC, Gram3r commented on ping-tinder/src/index.css
> +  margin: 15% 20% 15% 20%;
Исправил на конкретной размер тела, чтобы марджины подсчитывались автоматически, по идее так надежнее

2023-01-06 15:57 UTC, trixartem commented
✅ Принято

2023-01-06 15:57 UTC, closed without merging