Утюжников Дмитрий
itmo2022-verstka/task-2 pull request #5
Opened 2022-11-05 15:09 UTC by DimaUtyuz

2023-01-02 14:03 UTC, trixartem requested changes
В целом хорошо смотрится на мобилке в портретном режиме, но не очень на больших экранах или в landscape режиме

2023-01-02 14:03 UTC, trixartem commented on ping-tinder/src/index.html
> +      <div class="title">
Семантичнее h1

2023-01-02 14:03 UTC, trixartem commented on ping-tinder/src/index.html
> +        <text id="description" class="description">
Что за тег такой?

2023-01-02 14:03 UTC, trixartem commented on ping-tinder/src/index.html
> +        function next() {
Раз уж такая пляска, то почему не список объектов, а несколько массивов?

2023-01-02 14:03 UTC, trixartem commented on ping-tinder/src/index.css
> +  padding: 0 5%;
Проценты используются крайне редко, что бы соблюдать пропорции. Почему не px?

2023-01-02 14:03 UTC, trixartem commented on ping-tinder/src/index.css
> +  font-size: 10vw;
Не очень правильно выставлять шрифт от размера экрана - не всегда действует правило чем меньше экран, тем меньше шрифт. Лучше px, но с переходами в определенных местах(media)

2023-01-02 18:12 UTC, DimaUtyuz commented on ping-tinder/src/index.html
> +      <div class="title">
заменил

2023-01-02 18:14 UTC, DimaUtyuz commented on ping-tinder/src/index.html
> +        <text id="description" class="description">
Уже не помню, почему вообще решил его использовать. Убрал

2023-01-02 18:15 UTC, DimaUtyuz commented on ping-tinder/src/index.css
> +  font-size: 10vw;
Заменил на px и добавил переходы

2023-01-02 18:15 UTC, DimaUtyuz commented on ping-tinder/src/index.css
> +  padding: 0 5%;
Как раз, чтобы соблюдать пропорции отступов от краёв экрана

2023-01-02 18:16 UTC, DimaUtyuz commented on ping-tinder/src/index.html
> +        function next() {
Заменил на структуру

2023-01-02 18:19 UTC, DimaUtyuz commented
> В целом хорошо смотрится на мобилке в портретном режиме, но не очень на больших экранах или в landscape режиме

Замечания поправил. По картинкам из условия и тексту про стандартные размеры viewport я решил, что подразумевается верстка под мобильный вертикальный экран, поэтому на другом формате экрана может смотреться не очень хорошо

2023-01-03 09:16 UTC, trixartem commented
> [DimaUtyuz](/DimaUtyuz)

В этом и суть мобильной верстки - поддерживать оба вариант

2023-01-03 09:17 UTC, trixartem requested changes
Жду исправления горизонтального режима

2023-01-03 09:17 UTC, trixartem commented on ping-tinder/src/index.css
> +.buttons button img {
Почему такой сложный селектор? Нельзя обойтись одним классом?

2023-01-03 11:41 UTC, DimaUtyuz commented
> Жду исправления горизонтального режима

Добавил горизонтальный режим
![Screenshot from 2023-01-03 18-40-58](https://user-images.githubusercontent.com/71762910/210350504-a022f2cf-15f0-40a0-b4fc-56473c671250.png)

2023-01-06 15:59 UTC, trixartem commented
✅ Принято

2023-01-06 15:59 UTC, closed without merging