Брезгина Наталья
itmo2022-verstka/task-2 pull request #7
Opened 2022-11-06 12:48 UTC by natishark

2023-01-02 14:21 UTC, trixartem requested changes
Красивая анимация и иконки!
В горизонтальном режиме едет верстка, а в вертикальном режутся картинки
![image](https://user-images.githubusercontent.com/2376007/210243920-2adcddfc-de27-4249-9ed2-0b4c4ed2800c.png)

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  -webkit-box-shadow: 0 3px 8px 4px rgba(52, 52, 52, 0.2);
префиксы не нужны

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  color: white;
лучше hex - короче выходит #fff

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  width: 20vw;
Попробуйте использовать flex/grid вместо пропорций размеров

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.html
> +      PigTinder
Используйте семантичные теги

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  transform: translate(200%);
Анимация 🔥

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  object-fit: cover;
На мобилке картинка не влазит и ничего не видно
![image](https://user-images.githubusercontent.com/2376007/210243509-80680b55-4e25-4473-8e91-3cbe90e92f1c.png)

2023-01-02 14:21 UTC, trixartem commented on ping-tinder/src/index.css
> +  height: 20vh;
Лучше использовать принцип, если элемент имеет относительные размеры, то эти размер лучше считать от родителя. В противном случае эффект может быть не предскзуемым.

2023-01-09 06:15 UTC, natishark commented on ping-tinder/src/index.css
> +  -webkit-box-shadow: 0 3px 8px 4px rgba(52, 52, 52, 0.2);
Исправила

2023-01-09 06:16 UTC, natishark commented on ping-tinder/src/index.css
> +  color: white;
Конкретно в этом месте оставила rgba, но нормально его использовала с прозрачностью. В других местах сделала hex

2023-01-09 06:20 UTC, natishark commented on ping-tinder/src/index.css
> +  width: 20vw;
Не очень поняла, как совсем не задавать пропорции картинкам, но теперь есть только ширина/высота (в зависимости от ориентации) и считается в процентах.

А вот flex теперь используется (в другом комментарии)

2023-01-09 06:20 UTC, natishark commented on ping-tinder/src/index.html
> +      PigTinder
Добавлен тег `h1`

2023-01-09 06:29 UTC, natishark commented on ping-tinder/src/index.css
> +  object-fit: cover;
Сначала не очень поняла, что нужно именно чтобы всю картинку было видно, но на белом фоне или с картинкой квадратной формы при большой высотой экрана мне показалось выглядит не очень => 
Добавила background-image комфортного (как мне кажется) размера, а картинка теперь не обрезается.

Горизонтальный режим: картинка и линия иконок теперь во flex контейнере, блок с иконками тоже flex контейнер. при горизонтальной ориентации меняются направления расположения элементов (используется `@media`).

2023-01-09 06:33 UTC, natishark commented on ping-tinder/src/index.css
> +  height: 20vh;
Везде, где получилось, заменила `vh`/`vw` на `%`

2023-01-09 06:38 UTC, natishark commented
Теперь выглядит вот так:
![image](https://user-images.githubusercontent.com/81534178/211252384-98f50c96-45d2-44a0-86b1-461b27e55a76.png)
![image](https://user-images.githubusercontent.com/81534178/211252486-8d16c488-5ba9-45f4-862b-f244da99950d.png)

2023-01-10 12:57 UTC, trixartem commented
✅ Принято. Решение с фоном - крутое

2023-01-10 12:57 UTC, closed without merging